# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import todos_pb2 as todos__pb2


class TodoServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SaveTodo = channel.unary_unary(
        '/todo.TodoService/SaveTodo',
        request_serializer=todos__pb2.SaveTodoRequest.SerializeToString,
        response_deserializer=todos__pb2.TodoResponse.FromString,
        )
    self.ListTodo = channel.unary_unary(
        '/todo.TodoService/ListTodo',
        request_serializer=todos__pb2.ListTodoRequest.SerializeToString,
        response_deserializer=todos__pb2.TodoResponse.FromString,
        )
    self.ListAllTodo = channel.unary_stream(
        '/todo.TodoService/ListAllTodo',
        request_serializer=todos__pb2.ListAllTodoRequest.SerializeToString,
        response_deserializer=todos__pb2.ListAllTodoResponse.FromString,
        )
    self.DeleteTodo = channel.unary_unary(
        '/todo.TodoService/DeleteTodo',
        request_serializer=todos__pb2.DeleteTodoRequest.SerializeToString,
        response_deserializer=todos__pb2.TodoResponse.FromString,
        )
    self.EditTodo = channel.unary_unary(
        '/todo.TodoService/EditTodo',
        request_serializer=todos__pb2.EditTodoRequest.SerializeToString,
        response_deserializer=todos__pb2.TodoResponse.FromString,
        )
    self.ToggleStatus = channel.unary_unary(
        '/todo.TodoService/ToggleStatus',
        request_serializer=todos__pb2.ToggleStatusRequest.SerializeToString,
        response_deserializer=todos__pb2.TodoResponse.FromString,
        )


class TodoServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SaveTodo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListTodo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListAllTodo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteTodo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EditTodo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ToggleStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TodoServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SaveTodo': grpc.unary_unary_rpc_method_handler(
          servicer.SaveTodo,
          request_deserializer=todos__pb2.SaveTodoRequest.FromString,
          response_serializer=todos__pb2.TodoResponse.SerializeToString,
      ),
      'ListTodo': grpc.unary_unary_rpc_method_handler(
          servicer.ListTodo,
          request_deserializer=todos__pb2.ListTodoRequest.FromString,
          response_serializer=todos__pb2.TodoResponse.SerializeToString,
      ),
      'ListAllTodo': grpc.unary_stream_rpc_method_handler(
          servicer.ListAllTodo,
          request_deserializer=todos__pb2.ListAllTodoRequest.FromString,
          response_serializer=todos__pb2.ListAllTodoResponse.SerializeToString,
      ),
      'DeleteTodo': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteTodo,
          request_deserializer=todos__pb2.DeleteTodoRequest.FromString,
          response_serializer=todos__pb2.TodoResponse.SerializeToString,
      ),
      'EditTodo': grpc.unary_unary_rpc_method_handler(
          servicer.EditTodo,
          request_deserializer=todos__pb2.EditTodoRequest.FromString,
          response_serializer=todos__pb2.TodoResponse.SerializeToString,
      ),
      'ToggleStatus': grpc.unary_unary_rpc_method_handler(
          servicer.ToggleStatus,
          request_deserializer=todos__pb2.ToggleStatusRequest.FromString,
          response_serializer=todos__pb2.TodoResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'todo.TodoService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
