"""rev1.0 skimmedv3

Revision ID: 71b0c9983231
Revises: 8d24e52a48c9
Create Date: 2020-01-08 17:47:23.759702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71b0c9983231'
down_revision = '8d24e52a48c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
