"""rev1.0 skimmedv2

Revision ID: 8d24e52a48c9
Revises: d85d9c79ab5f
Create Date: 2020-01-08 16:12:38.634376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d24e52a48c9'
down_revision = 'd85d9c79ab5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
