"""Refactored NULL constraints

Revision ID: 8dcc0d17c3d1
Revises: 26a3f47e1078
Create Date: 2020-01-31 15:23:48.488270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dcc0d17c3d1'
down_revision = '26a3f47e1078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
