# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import todo.rpcs.todos_pb2 as todos__pb2


class TodoServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddTodo = channel.unary_unary(
        '/todo.TodoService/AddTodo',
        request_serializer=todos__pb2.Todo.SerializeToString,
        response_deserializer=todos__pb2.TodoResponse.FromString,
        )
    self.GetTodo = channel.unary_unary(
        '/todo.TodoService/GetTodo',
        request_serializer=todos__pb2.Todo.SerializeToString,
        response_deserializer=todos__pb2.TodoResponse.FromString,
        )
    self.ListAllTodo = channel.unary_stream(
        '/todo.TodoService/ListAllTodo',
        request_serializer=todos__pb2.EmptyRequest.SerializeToString,
        response_deserializer=todos__pb2.ListAllTodoResponse.FromString,
        )
    self.DeleteTodo = channel.unary_unary(
        '/todo.TodoService/DeleteTodo',
        request_serializer=todos__pb2.Todo.SerializeToString,
        response_deserializer=todos__pb2.TodoResponse.FromString,
        )
    self.EditTodo = channel.unary_unary(
        '/todo.TodoService/EditTodo',
        request_serializer=todos__pb2.Todo.SerializeToString,
        response_deserializer=todos__pb2.TodoResponse.FromString,
        )
    self.ToggleStatus = channel.unary_unary(
        '/todo.TodoService/ToggleStatus',
        request_serializer=todos__pb2.Todo.SerializeToString,
        response_deserializer=todos__pb2.TodoResponse.FromString,
        )


class TodoServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AddTodo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTodo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListAllTodo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteTodo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EditTodo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ToggleStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TodoServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddTodo': grpc.unary_unary_rpc_method_handler(
          servicer.AddTodo,
          request_deserializer=todos__pb2.Todo.FromString,
          response_serializer=todos__pb2.TodoResponse.SerializeToString,
      ),
      'GetTodo': grpc.unary_unary_rpc_method_handler(
          servicer.GetTodo,
          request_deserializer=todos__pb2.Todo.FromString,
          response_serializer=todos__pb2.TodoResponse.SerializeToString,
      ),
      'ListAllTodo': grpc.unary_stream_rpc_method_handler(
          servicer.ListAllTodo,
          request_deserializer=todos__pb2.EmptyRequest.FromString,
          response_serializer=todos__pb2.ListAllTodoResponse.SerializeToString,
      ),
      'DeleteTodo': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteTodo,
          request_deserializer=todos__pb2.Todo.FromString,
          response_serializer=todos__pb2.TodoResponse.SerializeToString,
      ),
      'EditTodo': grpc.unary_unary_rpc_method_handler(
          servicer.EditTodo,
          request_deserializer=todos__pb2.Todo.FromString,
          response_serializer=todos__pb2.TodoResponse.SerializeToString,
      ),
      'ToggleStatus': grpc.unary_unary_rpc_method_handler(
          servicer.ToggleStatus,
          request_deserializer=todos__pb2.Todo.FromString,
          response_serializer=todos__pb2.TodoResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'todo.TodoService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
