# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todos.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='todos.proto',
  package='todo',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0btodos.proto\x12\x04todo\x1a\x1fgoogle/protobuf/timestamp.proto\"\x0e\n\x0c\x45mptyRequest\"V\n\x13ListAllTodoResponse\x12%\n\x06status\x18\x01 \x01(\x0b\x32\x15.todo.OperationErrors\x12\x18\n\x04todo\x18\x02 \x01(\x0b\x32\n.todo.Todo\"O\n\x0cTodoResponse\x12%\n\x06status\x18\x01 \x01(\x0b\x32\x15.todo.OperationErrors\x12\x18\n\x04todo\x18\x02 \x01(\x0b\x32\n.todo.Todo\"\xb8\x01\n\x04Todo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12 \n\x06status\x18\x04 \x01(\x0e\x32\x10.todo.TodoStatus\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"=\n\x0fOperationErrors\x12\x1a\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x0c.todo.Status\x12\x0e\n\x06\x65rrors\x18\x02 \x03(\t*D\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x12\r\n\tNOT_FOUND\x10\x02\x12\x0b\n\x07UPDATED\x10\x04\x12\x0b\n\x07\x44\x45LETED\x10\x05*2\n\nTodoStatus\x12\x07\n\x03NEW\x10\x00\x12\x0c\n\x08PROGRESS\x10\x01\x12\r\n\tCOMPLETED\x10\x02\x32\xb9\x02\n\x0bTodoService\x12+\n\x07\x41\x64\x64Todo\x12\n.todo.Todo\x1a\x12.todo.TodoResponse\"\x00\x12+\n\x07GetTodo\x12\n.todo.Todo\x1a\x12.todo.TodoResponse\"\x00\x12@\n\x0bListAllTodo\x12\x12.todo.EmptyRequest\x1a\x19.todo.ListAllTodoResponse\"\x00\x30\x01\x12.\n\nDeleteTodo\x12\n.todo.Todo\x1a\x12.todo.TodoResponse\"\x00\x12,\n\x08\x45\x64itTodo\x12\n.todo.Todo\x1a\x12.todo.TodoResponse\"\x00\x12\x30\n\x0cToggleStatus\x12\n.todo.Todo\x1a\x12.todo.TodoResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])

_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='todo.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOT_FOUND', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UPDATED', index=3, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETED', index=4, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=489,
  serialized_end=557,
)
_sym_db.RegisterEnumDescriptor(_STATUS)

Status = enum_type_wrapper.EnumTypeWrapper(_STATUS)
_TODOSTATUS = _descriptor.EnumDescriptor(
  name='TodoStatus',
  full_name='todo.TodoStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NEW', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROGRESS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPLETED', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=559,
  serialized_end=609,
)
_sym_db.RegisterEnumDescriptor(_TODOSTATUS)

TodoStatus = enum_type_wrapper.EnumTypeWrapper(_TODOSTATUS)
OK = 0
ERROR = 1
NOT_FOUND = 2
UPDATED = 4
DELETED = 5
NEW = 0
PROGRESS = 1
COMPLETED = 2



_EMPTYREQUEST = _descriptor.Descriptor(
  name='EmptyRequest',
  full_name='todo.EmptyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=68,
)


_LISTALLTODORESPONSE = _descriptor.Descriptor(
  name='ListAllTodoResponse',
  full_name='todo.ListAllTodoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='todo.ListAllTodoResponse.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='todo', full_name='todo.ListAllTodoResponse.todo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=156,
)


_TODORESPONSE = _descriptor.Descriptor(
  name='TodoResponse',
  full_name='todo.TodoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='todo.TodoResponse.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='todo', full_name='todo.TodoResponse.todo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=237,
)


_TODO = _descriptor.Descriptor(
  name='Todo',
  full_name='todo.Todo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='todo.Todo.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='todo.Todo.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='todo.Todo.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='todo.Todo.status', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='todo.Todo.created_at', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='updated_at', full_name='todo.Todo.updated_at', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=424,
)


_OPERATIONERRORS = _descriptor.Descriptor(
  name='OperationErrors',
  full_name='todo.OperationErrors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='todo.OperationErrors.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errors', full_name='todo.OperationErrors.errors', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=426,
  serialized_end=487,
)

_LISTALLTODORESPONSE.fields_by_name['status'].message_type = _OPERATIONERRORS
_LISTALLTODORESPONSE.fields_by_name['todo'].message_type = _TODO
_TODORESPONSE.fields_by_name['status'].message_type = _OPERATIONERRORS
_TODORESPONSE.fields_by_name['todo'].message_type = _TODO
_TODO.fields_by_name['status'].enum_type = _TODOSTATUS
_TODO.fields_by_name['created_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_TODO.fields_by_name['updated_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_OPERATIONERRORS.fields_by_name['code'].enum_type = _STATUS
DESCRIPTOR.message_types_by_name['EmptyRequest'] = _EMPTYREQUEST
DESCRIPTOR.message_types_by_name['ListAllTodoResponse'] = _LISTALLTODORESPONSE
DESCRIPTOR.message_types_by_name['TodoResponse'] = _TODORESPONSE
DESCRIPTOR.message_types_by_name['Todo'] = _TODO
DESCRIPTOR.message_types_by_name['OperationErrors'] = _OPERATIONERRORS
DESCRIPTOR.enum_types_by_name['Status'] = _STATUS
DESCRIPTOR.enum_types_by_name['TodoStatus'] = _TODOSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmptyRequest = _reflection.GeneratedProtocolMessageType('EmptyRequest', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYREQUEST,
  '__module__' : 'todos_pb2'
  # @@protoc_insertion_point(class_scope:todo.EmptyRequest)
  })
_sym_db.RegisterMessage(EmptyRequest)

ListAllTodoResponse = _reflection.GeneratedProtocolMessageType('ListAllTodoResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTALLTODORESPONSE,
  '__module__' : 'todos_pb2'
  # @@protoc_insertion_point(class_scope:todo.ListAllTodoResponse)
  })
_sym_db.RegisterMessage(ListAllTodoResponse)

TodoResponse = _reflection.GeneratedProtocolMessageType('TodoResponse', (_message.Message,), {
  'DESCRIPTOR' : _TODORESPONSE,
  '__module__' : 'todos_pb2'
  # @@protoc_insertion_point(class_scope:todo.TodoResponse)
  })
_sym_db.RegisterMessage(TodoResponse)

Todo = _reflection.GeneratedProtocolMessageType('Todo', (_message.Message,), {
  'DESCRIPTOR' : _TODO,
  '__module__' : 'todos_pb2'
  # @@protoc_insertion_point(class_scope:todo.Todo)
  })
_sym_db.RegisterMessage(Todo)

OperationErrors = _reflection.GeneratedProtocolMessageType('OperationErrors', (_message.Message,), {
  'DESCRIPTOR' : _OPERATIONERRORS,
  '__module__' : 'todos_pb2'
  # @@protoc_insertion_point(class_scope:todo.OperationErrors)
  })
_sym_db.RegisterMessage(OperationErrors)



_TODOSERVICE = _descriptor.ServiceDescriptor(
  name='TodoService',
  full_name='todo.TodoService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=612,
  serialized_end=925,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddTodo',
    full_name='todo.TodoService.AddTodo',
    index=0,
    containing_service=None,
    input_type=_TODO,
    output_type=_TODORESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetTodo',
    full_name='todo.TodoService.GetTodo',
    index=1,
    containing_service=None,
    input_type=_TODO,
    output_type=_TODORESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListAllTodo',
    full_name='todo.TodoService.ListAllTodo',
    index=2,
    containing_service=None,
    input_type=_EMPTYREQUEST,
    output_type=_LISTALLTODORESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteTodo',
    full_name='todo.TodoService.DeleteTodo',
    index=3,
    containing_service=None,
    input_type=_TODO,
    output_type=_TODORESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='EditTodo',
    full_name='todo.TodoService.EditTodo',
    index=4,
    containing_service=None,
    input_type=_TODO,
    output_type=_TODORESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ToggleStatus',
    full_name='todo.TodoService.ToggleStatus',
    index=5,
    containing_service=None,
    input_type=_TODO,
    output_type=_TODORESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TODOSERVICE)

DESCRIPTOR.services_by_name['TodoService'] = _TODOSERVICE

# @@protoc_insertion_point(module_scope)
